Challenge 10
17kikak/js03 pull request #1
Opened 2017-09-08 23:52 UTC by 17kikak

Ditto
@griselleong
@rickyc

2017-09-09 00:03 UTC, rickyc approved these changes

2017-09-09 00:03 UTC, rickyc commented on challenge-10/index.html
> +      const cat2 = {name: "ditto"};
So I change the second cat name to "Kika" and it still returned `true` :(

2017-09-09 00:03 UTC, rickyc commented on challenge-10/index.html
> +        if (a.keys === b.keys){
You can simplify this by writing the following.

```js
console.log(a.keys === b.keys);
```

2017-09-09 00:05 UTC, rickyc requested changes
Try the following scenarios.

```js
const cat1 = { name: "Ditto" };
const cat2 = { name: "Kika" };
```
```js
const cat1 = { name: "Ditto" };
const cat2 = { name: "Ditto", age: 10 };
```

2017-09-09 01:14 UTC, 17kikak commented
Could you review the updated code? I'm not quite sure if put it up here properly...

2017-09-10 11:25 UTC, rickyc reviewed
Just a few comments for your pull request, otherwise It looks good. 

Just a minor thing, not too important, but the objective was to return whether the objects matched (`true` or `false`).

Right now it prints `true` and `false` together. In the case there are multiple keys.

```js
const cat = { name: "Ditto", animal: "cat" }
const dog = { name: "Ditto", animal: "dog" }
```

This should would log `true`, then `false`. We just want to see one `false`.

2017-09-10 11:25 UTC, rickyc commented on challenge-10/index.html
> +      let ditto = (a, b) => {
`const ditto`

2017-09-10 11:25 UTC, rickyc commented on challenge-10/index.html
> +        let keysa = Object.keys(cat1);
Looks like `keysA` and `keysB` can also be a `const` since we aren't assigning the variables with another value.

2017-09-10 11:25 UTC, rickyc commented on challenge-10/index.html
> +        console.log(b[keysb]);
👍 `console.log` are good for debugging, but if you are finished with your work, make sure to remove them so the code looks cleaner.

2017-09-10 11:25 UTC, rickyc commented on challenge-10/index.html
> +        for(let i = 0; i < keysa.length; i++){
Make sure to indent inside the `if` statement

2017-09-10 11:25 UTC, rickyc commented on challenge-10/index.html
> +          if (keysa[i] === keysb[i] && a[keysa[i]] === b[keysb[i]]) {
You actually don't need an if statement! If you set line 19 into a variable, you can just print out that variable.

2017-09-10 11:25 UTC, rickyc approved these changes
Feel free to merge it in when you are done with this!

2017-09-10 19:09 UTC, merged